### ISSUE TITLE
AddLinesToList() method accepts wrong inputs

### ISSUE THREAD

**Issue by andulica** [andulica/SlotMachineExercise#53]
The following method accepts wrong inputs as valid ones as long as they are number. Need a better handling of user input
https://github.com/andulica/SlotMachineExercise/blob/4c429a9f8f4a525df10be8278d77351a52797194/GameLogic.cs#L71-L99

**Comment by mayisa87** [comment]
This method is a bit tricky from the beginning, as you try to cover entering line values and asking user at the same time if he wants to continue adding etc.

First of all, you could add the choseLine only to list, if the value is between MIN_LINE_TO_PLAY  and MAX_LINE_TO_PLAY, that would resolve the error, that you add it always to list.

And I'm thinking about, what if you do only one while loop instead of two?
You could have only one while loop in UI.GetValidLineSelection(), GetValidLineSelection() will return List<int> at the end.

- each iteration the user is asked for an line number.
- In case that parse is OK, you do your ifs as you have it already now in the AddLinesList() method in Logic.
- If the number is not valid, ask user if he wants to stop entering values, if "y" return the current state of list and break loop

**Comment by andulica** [comment]
Making the UI.GetValidLineSelection more complex would not violate the principle of keeping UI simple and GameLogic the business logic ?

**Comment by mayisa87** [comment]
I think like it is currently it is OK. Anyway I have a few things you could improve.
First of all, you still got a but, when entering wrong values. Like -2:

![image](https://github.com/andulica/SlotMachineExercise/assets/130921606/a222afa2-e444-4176-a875-20e93838eaae)

That's why I wrote: "First of all, you could add the choseLine only to list, if the value is between MIN_LINE_TO_PLAY and MAX_LINE_TO_PLAY, that would resolve the error, that you add it always to list."

And you can change your GetValidLines method and remove the marked parts, so it will be shorter. I think then it is fine!

![image](https://github.com/andulica/SlotMachineExercise/assets/130921606/905943bf-1f10-49cc-be7f-d54a8d4c1c11)
